# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\AppData\Roaming\Anki2\addons21\hjp-bilink\.useless\configdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.resize(1013, 416)
        self.horizontalLayout = QtWidgets.QHBoxLayout(config)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.configTable = QtWidgets.QTableView(config)
        self.configTable.setObjectName("configTable")
        self.configTable.horizontalHeader().setCascadingSectionResizes(True)
        self.configTable.horizontalHeader().setDefaultSectionSize(150)
        self.configTable.horizontalHeader().setSortIndicatorShown(True)
        self.configTable.horizontalHeader().setStretchLastSection(True)
        self.configTable.verticalHeader().setVisible(False)
        self.configTable.verticalHeader().setDefaultSectionSize(20)
        self.configTable.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout.addWidget(self.configTable)
        self.textBrowser = QtWidgets.QTextBrowser(config)
        self.textBrowser.setTabletTracking(False)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)

        self.retranslateUi(config)
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "config"))
        self.textBrowser.setHtml(_translate("config",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
