# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\AppData\Roaming\Anki2\addons21\hjp-bilink\.useless\anchordialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_anchor(object):
    def setupUi(self, anchor):
        anchor.setObjectName("anchor")
        anchor.resize(416, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(anchor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.anchorTree = QtWidgets.QTreeView(anchor)
        self.anchorTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.anchorTree.setDragEnabled(True)
        self.anchorTree.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.anchorTree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.anchorTree.setAlternatingRowColors(True)
        self.anchorTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)

        self.anchorTree.setAnimated(True)
        self.anchorTree.setWordWrap(True)
        self.anchorTree.setObjectName("anchorTree")
        self.anchorTree.header().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.anchorTree)
        self.self_desc_label = QtWidgets.QLabel(anchor)
        self.self_desc_label.setObjectName("self_desc")
        self.self_desc_label.setText("self_desc")
        self.self_desc = QtWidgets.QLineEdit(self.self_desc_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.addWidget(self.self_desc_label)
        self.horizontalLayout_2.addWidget(self.self_desc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(anchor)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.retranslateUi(anchor)
        QtCore.QMetaObject.connectSlotsByName(anchor)

    def retranslateUi(self, anchor):
        _translate = QtCore.QCoreApplication.translate
        anchor.setWindowTitle(_translate("anchor", "anchor"))
        self.label.setText(_translate("anchor",
                                      """右键可新建group,可删除link,可拖拽link/group形成层级结构,可双击预览,可多选操作
self_desc是anchor所属的卡片本身的名字，链接时会提取他，如果为空会从卡片正文中提取。
                                      """))
